// Vercel serverless function entry point.
// Loads the esbuild-bundled Hono app (generated at build time).
// @ts-ignore — _bundle.mjs is generated by scripts/build-api.mjs
export { default } from "./_bundle.mjs";
